apiVersion: v2
name: kafka-stack
description: A Helm chart for kafka with mongodb.
version: 0.1.0
appVersion: 1.0.0
dependencies:
  # - name: mongodb
  #   version: "0.1.0"
  #   repository: "file://./charts/mongodb"
  #   enabled: true
  - name: kafka
    version: "0.1.0"
    repository: "file://./charts/kafka"
    enabled: true
  - name: kafka-ui
    version: "0.1.0"
    repository: "file://./charts/kafka-ui"
    enabled: true
  - name: prometheus
    version: "0.1.0"
    repository: "file://./charts/prometheus"
    enabled: true
  - name: grafana
    version: "0.1.0"
    repository: "file://./charts/grafana"
    enabled: true
